const $=id=>document.getElementById(id), key='tabi-map-v1';let data=null,current=null,selectedId=null,saved=[],entries=[];
try {const newer=localStorage.getItem('michi-v2');if(newer){const b=LifeBackup.validate(JSON.parse(newer));saved=b.trips;entries=b.entries;}else{saved=JSON.parse(localStorage.getItem(key)||'[]');}}catch{}if(!Array.isArray(saved))saved=[];
let map=null,layer=null;if(window.L){map=L.map('map').setView([36.3,138],5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);layer=L.featureGroup().addTo(map)}else $('map').textContent='地図を読み込めませんでした。インターネット接続を確認してください。記録の解析は利用できます。';
function day(t){const d=new Date(t);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function status(t){$('status').textContent=t}function write(){try{localStorage.setItem('michi-v2',JSON.stringify({format:'michi-v2',trips:saved,entries}));return true}catch{status('端末への保存に失敗しました。バックアップを書き出して記録を保管してください。');return false}}
function setData(d){data=d;const dates=[...d.visits,...d.paths].map(x=>day(x.start)).sort();$('from').value=dates[0];$('to').value=dates.at(-1);filter()}
function filter(){if(!data)return status('先にファイルまたはサンプルを読み込んでください。');const from=$('from').value,to=$('to').value;if(!from||!to||from>to)return status('開始日と終了日を確認してください。');data.cards ||= {};current={visits:data.visits.filter(x=>day(x.start)>=from&&day(x.start)<=to),paths:data.paths.filter(x=>day(x.start)>=from&&day(x.start)<=to),cards:data.cards||{}};render();}
let candidates=[],candidatePage=0,matchWorker=null,matchSequence=0;
function render(){if(layer)layer.clearLayers();$('places').replaceChildren();$('count').textContent=`${current.visits.length}件の訪問・${current.paths.length}件の移動`;$('title').textContent=`${$('from').value} 〜 ${$('to').value}`;
if(layer){const stride=Math.max(1,Math.ceil(current.paths.length/500));for(let i=0;i<current.paths.length;i+=stride){const pts=current.paths[i].points;if(pts.length>1){const every=Math.max(1,Math.ceil(pts.length/300));const sample=pts.filter((_,j)=>j%every===0);sample.push(pts.at(-1));L.polyline(sample,{color:'#55876b',weight:3,opacity:.5}).addTo(layer)}}const vStride=Math.max(1,Math.ceil(current.visits.length/1000));for(let i=0;i<current.visits.length;i+=vStride){const v=current.visits[i];L.circleMarker([v.lat,v.lng],{radius:3,color:'#7e9883',weight:1}).addTo(layer)}if(layer.getLayers().length)map.fitBounds(layer.getBounds(),{padding:[30,30],maxZoom:14})}
findCandidates()}
function findCandidates(){if(!current)return;if(matchWorker)matchWorker.terminate();const sequence=++matchSequence;candidatePage=0;candidates=[];$('places').replaceChildren();$('candidate-status').textContent='配布場所と訪問記録を照合しています…';const w=new Worker('match-worker.js?v=5');matchWorker=w;w.onmessage=e=>{w.terminate();if(sequence!==matchSequence)return;if(!e.data.ok){$('candidate-status').textContent='配布場所との照合に失敗しました。ページを再読み込みしてください。';return}candidates=e.data.result;renderCandidates()};w.onerror=()=>{w.terminate();if(sequence===matchSequence)$('candidate-status').textContent='配布場所データを読み込めませんでした。ページを再読み込みしてください。'};w.postMessage({visits:current.visits,radius:Number($('radius').value)})}
function renderCandidates(){const el=$('places');el.replaceChildren();const pages=Math.max(1,Math.ceil(candidates.length/20));candidatePage=Math.min(candidatePage,pages-1);$('candidate-status').textContent=candidates.length?`${candidates.length}種類の取得候補。カードごとにまとめています。`:'この範囲の取得候補はありません。距離を広げると候補が見つかる場合があります。座標未収録の配布場所と移動経路だけの記録は照合対象外です。';$('page-number').textContent=`${candidatePage+1} / ${pages}`;$('previous').disabled=candidatePage===0;$('next').disabled=candidatePage>=pages-1;
for(const c of candidates.slice(candidatePage*20,candidatePage*20+20)){const state=current.cards[c.id]||{status:'candidate',note:''};const card=document.createElement('div');card.className='place';const h=document.createElement('h3');h.textContent=c.name;const info=document.createElement('p');info.textContent=`${c.place}\n${c.address}\n訪問 ${day(c.first)}${day(c.first)!==day(c.last)?'〜'+day(c.last):''} ｜ 最短 約${Math.round(c.distance)}m（推定位置）`;info.style.whiteSpace='pre-wrap';const select=document.createElement('select');select.setAttribute('aria-label',c.name+'の取得状態');for(const [value,text] of [['candidate','未確認'],['acquired','取得済み'],['not-acquired','取得していない']]){const opt=document.createElement('option');opt.value=value;opt.textContent=text;select.append(opt)}select.value=state.status;select.onchange=()=>{current.cards[c.id]={...state,status:select.value};renderCandidates()};const buttons=document.createElement('div');buttons.className='actions';const mapButton=document.createElement('button');mapButton.className='secondary';mapButton.textContent='配布場所を地図で見る';mapButton.onclick=()=>{if(map){map.setView([c.lat,c.lng],16);const label=document.createElement('span');label.textContent=c.name+' / '+c.place;L.popup().setLatLng([c.lat,c.lng]).setContent(label).openOn(map)}};const link=document.createElement('a');link.textContent='配布情報を確認';link.href=/^https?:/.test(c.source)?c.source:'https://www.gk-p.jp/mhcard/';link.target='_blank';link.rel='noopener noreferrer';buttons.append(mapButton,link);card.append(h);if(c.image){const imageLink=document.createElement('a');imageLink.href=c.image;imageLink.target='_blank';imageLink.rel='noopener noreferrer';imageLink.className='card-image-link';imageLink.setAttribute('aria-label',c.name+'のカード画像を大きく見る');const thumbnail=document.createElement('img');thumbnail.src=c.image;thumbnail.alt=c.name+'のマンホールカード';thumbnail.loading='lazy';thumbnail.decoding='async';thumbnail.referrerPolicy='no-referrer';thumbnail.className='card-image';thumbnail.onerror=()=>{imageLink.textContent='カード画像を開く';};imageLink.append(thumbnail);card.append(imageLink);const credit=document.createElement('a');credit.href='https://www.gk-p.jp/mhcard/?pref=zenkoku';credit.target='_blank';credit.rel='noopener noreferrer';credit.className='image-credit';credit.textContent='画像：下水道広報プラットホーム（GKP）';card.append(credit)}card.append(info,select,buttons);if(state.status==='acquired'){const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='このカードのメモ';details.append(summary);details.ontoggle=()=>{if(!details.open||details.querySelector('textarea'))return;const note=document.createElement('textarea');note.setAttribute('aria-label',c.name+'のメモ');note.placeholder='取得したときの思い出や土地の学び';note.value=state.note;note.oninput=()=>{state.note=note.value;current.cards[c.id]={...state}};details.append(note)};card.append(details)}el.append(card)}}
$('radius').onchange=findCandidates;$('previous').onclick=()=>{candidatePage--;renderCandidates()};$('next').onclick=()=>{candidatePage++;renderCandidates()};
$('catalog-info').textContent=`GKP配布場所一覧（${CardCatalog.checked}取得）を基に、${CardCatalog.cardsCovered} / ${CardCatalog.cardsTotal}種類のカードを照合。住所から推定した座標を使用。広い期間の地図表示は間引き、候補の照合は全訪問記録で行います。`;
let timelineJob=0;
function parseTimelineFile(file){return new Promise((resolve,reject)=>{const worker=new Worker('timeline-worker.js?v=3');worker.onmessage=e=>{worker.terminate();if(e.data.ok)resolve(e.data.result);else{const error=new Error(e.data.message);error.diagnostic=e.data.diagnostic;reject(error)}};worker.onerror=()=>{worker.terminate();reject(new Error('ファイルを解析できませんでした。端末のメモリ不足や読み込み処理のエラーが考えられます。'))};worker.postMessage(file)})}
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const job=++timelineJob;$('file').disabled=true;hideDiagnostic();status(`読み込み中（${(f.size/1024/1024).toFixed(1)}MB）… 大きなファイルは時間がかかります。`);try{const parsed=await parseTimelineFile(f);if(job!==timelineJob)return;selectedId=null;setData(parsed);status(`読み込み完了：訪問 ${parsed.visits.length}件、移動 ${parsed.paths.length}件。${parsed.ignored?`${parsed.ignored}件は日時や座標が不足しているため除外しました。`:''} 編集後は「表示中の旅を端末に保存」を押してください。`)}catch(err){if(job!==timelineJob)return;if(err.diagnostic)showDiagnostic(err.diagnostic);status(err.message)}finally{if(job===timelineJob){$('file').disabled=false;e.target.value=''}}};
$('filter').onclick=filter;
$('save').onclick=()=>{if(!current||!current.visits.length&&!current.paths.length)return status('保存できる記録がありません。');const trip={id:selectedId||crypto.randomUUID(),title:`${$('from').value}〜${$('to').value}`,from:$('from').value,to:$('to').value,...structuredClone(current)};const i=saved.findIndex(x=>x.id===trip.id);if(i<0)saved.push(trip);else saved[i]=trip;selectedId=trip.id;if(write())status('このブラウザに保存しました。別の端末へ移すときはバックアップを書き出してください。');renderSaved()};
function renderSaved(){$('saved').replaceChildren();if(!saved.length)$('saved').textContent='保存した旅はまだありません。';saved.forEach(t=>{const row=document.createElement('div');row.className='savedrow';const open=document.createElement('button');open.className='secondary';open.textContent=t.title;open.onclick=()=>{selectedId=t.id;data=structuredClone(t);$('from').value=t.from;$('to').value=t.to;filter();status('保存した旅を開きました。編集後は保存を押してください。')};const del=document.createElement('button');del.className='secondary';del.textContent='削除';del.onclick=()=>{if(confirm('この旅を端末から削除しますか？')){saved=saved.filter(x=>x.id!==t.id);write();renderSaved()}};row.append(open,del);$('saved').append(row)})}
function downloadBackup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'michi-v2',trips:saved,entries},null,2)],{type:'application/json'}));a.download=`Life Atlas-${day(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('export').onclick=downloadBackup;
$('restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100*1024*1024)throw Error('ファイルが100MBを超えています。');const b=LifeBackup.validate(JSON.parse((await f.text()).replace(/^\uFEFF/,'')));if(!confirm(`旅 ${b.trips.length}件を取り込み、現在の旅 ${saved.length}件を置き換えます。以前の版で作った追加記録もバックアップ内に保持します。取り込み前に現在の記録をバックアップしましたか？`))return;
const oldSaved=saved,oldEntries=entries;saved=b.trips;entries=b.entries;if(!write()){saved=oldSaved;entries=oldEntries;return}data=current=null;selectedId=null;if(matchWorker)matchWorker.terminate();matchSequence++;candidates=[];$('candidate-status').textContent='旅行期間を選ぶと取得候補を表示します。';if(layer)layer.clearLayers();$('places').replaceChildren();$('title').textContent='旅の軌跡';$('count').textContent='0件の記録';renderSaved();status('バックアップを取り込みました。保存した旅から記録を開けます。');}catch(err){status(err.message||'バックアップを読み込めませんでした。')}finally{e.target.value=''}};
$('demo').onclick=()=>{const loc=CardCatalog.locations.find(l=>l.name.includes('札幌市'))||CardCatalog.locations[0];if(!loc)return;selectedId=null;setData({visits:[{id:'sample',start:'2026-10-01T01:00:00Z',lat:loc.lat,lng:loc.lng,name:'配布場所のサンプル訪問',card:false,note:''}],paths:[],cards:{}});status('動作確認用の架空の訪問です。ご自身の取得記録ではありません。')};renderSaved();

function showDiagnostic(text){let box=document.getElementById('json-diagnostic');if(!box){box=document.createElement('details');box.id='json-diagnostic';const summary=document.createElement('summary');summary.textContent='ファイル構造の診断（項目名と型のみ）';const info=document.createElement('p');info.className='hint';info.textContent='日時・座標・訪問先などの値は含みません。この欄のテキストをコピーしてチャットに貼ると、対応方法を確認できます。';const area=document.createElement('textarea');area.readOnly=true;area.setAttribute('aria-label','ファイル構造の診断');area.style.cssText='width:100%;height:230px;font-family:monospace;font-size:12px';box.append(summary,info,area);$('status').after(box)}box.hidden=false;box.open=true;box.querySelector('textarea').value=text}
function hideDiagnostic(){const box=document.getElementById('json-diagnostic');if(box)box.hidden=true}
