const $=id=>document.getElementById(id), key='tabi-map-v1';let data=null,current=null,selectedId=null,saved=[],entries=[];
try {const newer=localStorage.getItem('michi-v2');if(newer){const b=LifeBackup.validate(JSON.parse(newer));saved=b.trips;entries=b.entries;}else{saved=JSON.parse(localStorage.getItem(key)||'[]');}}catch{}if(!Array.isArray(saved))saved=[];
let map=null,layer=null;if(window.L){map=L.map('map').setView([36.3,138],5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);layer=L.featureGroup().addTo(map)}else $('map').textContent='地図を読み込めませんでした。インターネット接続を確認してください。記録の解析は利用できます。';
function day(t){const d=new Date(t);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function status(t){$('status').textContent=t}function write(){try{localStorage.setItem('michi-v2',JSON.stringify({format:'michi-v2',trips:saved,entries}));return true}catch{status('端末への保存に失敗しました。バックアップを書き出して記録を保管してください。');return false}}
function setData(d){data=d;const dates=[...d.visits,...d.paths].map(x=>day(x.start)).sort();$('from').value=dates[0];$('to').value=dates.at(-1);filter()}
function filter(){if(!data)return status('先にファイルまたはサンプルを読み込んでください。');const from=$('from').value,to=$('to').value;if(!from||!to||from>to)return status('開始日と終了日を確認してください。');current={visits:data.visits.filter(x=>day(x.start)>=from&&day(x.start)<=to),paths:data.paths.filter(x=>day(x.start)>=from&&day(x.start)<=to)};render();}
function render(){if(layer)layer.clearLayers();$('places').replaceChildren();$('count').textContent=`${current.visits.length}件の訪問・${current.paths.length}件の移動`;$('title').textContent=`${$('from').value} 〜 ${$('to').value}`;current.paths.forEach(p=>{if(layer){if(p.points.length>1)L.polyline(p.points,{color:'#55876b',weight:4,opacity:.65}).addTo(layer);else L.circleMarker(p.points[0],{radius:2,color:'#55876b'}).addTo(layer)}});current.visits.forEach(v=>{let marker=null;if(layer){marker=L.marker([v.lat,v.lng]).addTo(layer);const label=document.createElement('span');label.textContent=v.name;marker.bindPopup(label)}const card=document.createElement('div');card.className='place';const name=document.createElement('input');name.value=v.name;name.setAttribute('aria-label','訪問先の名前');name.oninput=()=>v.name=name.value;const time=document.createElement('small');time.textContent=new Date(v.start).toLocaleString('ja-JP');const check=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.checked=!!v.card;box.onchange=()=>v.card=box.checked;check.append(box,document.createTextNode('マンホールカードを取得'));const note=document.createElement('textarea');note.placeholder='土地の歴史、地名の読み方、旅の思い出…';note.value=v.note||'';note.setAttribute('aria-label','学びのメモ');note.oninput=()=>v.note=note.value;const btn=document.createElement('button');btn.textContent='地図で見る';btn.onclick=()=>{if(map){map.setView([v.lat,v.lng],14);marker.openPopup()}};card.append(name,time,check,note,btn);$('places').append(card)});if(layer&&layer.getLayers().length)map.fitBounds(layer.getBounds(),{padding:[30,30],maxZoom:14});if(!current.visits.length)$('places').textContent='この期間の訪問先はありません。移動記録だけのデータには、訪問先のメモは追加できません。';}
let timelineJob=0;
function parseTimelineFile(file){return new Promise((resolve,reject)=>{const worker=new Worker('timeline-worker.js?v=3');worker.onmessage=e=>{worker.terminate();if(e.data.ok)resolve(e.data.result);else{const error=new Error(e.data.message);error.diagnostic=e.data.diagnostic;reject(error)}};worker.onerror=()=>{worker.terminate();reject(new Error('ファイルを解析できませんでした。端末のメモリ不足や読み込み処理のエラーが考えられます。'))};worker.postMessage(file)})}
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;const job=++timelineJob;$('file').disabled=true;hideDiagnostic();status(`読み込み中（${(f.size/1024/1024).toFixed(1)}MB）… 大きなファイルは時間がかかります。`);try{const parsed=await parseTimelineFile(f);if(job!==timelineJob)return;selectedId=null;setData(parsed);status(`読み込み完了：訪問 ${parsed.visits.length}件、移動 ${parsed.paths.length}件。${parsed.ignored?`${parsed.ignored}件は日時や座標が不足しているため除外しました。`:''} 編集後は「表示中の旅を端末に保存」を押してください。`)}catch(err){if(job!==timelineJob)return;if(err.diagnostic)showDiagnostic(err.diagnostic);status(err.message)}finally{if(job===timelineJob){$('file').disabled=false;e.target.value=''}}};
$('filter').onclick=filter;
$('save').onclick=()=>{if(!current||!current.visits.length&&!current.paths.length)return status('保存できる記録がありません。');const trip={id:selectedId||crypto.randomUUID(),title:`${$('from').value}〜${$('to').value}`,from:$('from').value,to:$('to').value,...structuredClone(current)};const i=saved.findIndex(x=>x.id===trip.id);if(i<0)saved.push(trip);else saved[i]=trip;selectedId=trip.id;if(write())status('このブラウザに保存しました。別の端末へ移すときはバックアップを書き出してください。');renderSaved()};
function renderSaved(){$('saved').replaceChildren();if(!saved.length)$('saved').textContent='保存した旅はまだありません。';saved.forEach(t=>{const row=document.createElement('div');row.className='savedrow';const open=document.createElement('button');open.className='secondary';open.textContent=t.title;open.onclick=()=>{selectedId=t.id;data=structuredClone(t);$('from').value=t.from;$('to').value=t.to;filter();status('保存した旅を開きました。編集後は保存を押してください。')};const del=document.createElement('button');del.className='secondary';del.textContent='削除';del.onclick=()=>{if(confirm('この旅を端末から削除しますか？')){saved=saved.filter(x=>x.id!==t.id);write();renderSaved()}};row.append(open,del);$('saved').append(row)})}
function downloadBackup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({format:'michi-v2',trips:saved,entries},null,2)],{type:'application/json'}));a.download=`Life Atlas-${day(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('export').onclick=downloadBackup;
$('restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>100*1024*1024)throw Error('ファイルが100MBを超えています。');const b=LifeBackup.validate(JSON.parse((await f.text()).replace(/^\uFEFF/,'')));if(!confirm(`旅 ${b.trips.length}件を取り込み、現在の旅 ${saved.length}件を置き換えます。以前の版で作った追加記録もバックアップ内に保持します。取り込み前に現在の記録をバックアップしましたか？`))return;
const oldSaved=saved,oldEntries=entries;saved=b.trips;entries=b.entries;if(!write()){saved=oldSaved;entries=oldEntries;return}data=current=null;selectedId=null;if(layer)layer.clearLayers();$('places').replaceChildren();$('title').textContent='旅の軌跡';$('count').textContent='0件の記録';renderSaved();status('バックアップを取り込みました。保存した旅から記録を開けます。');}catch(err){status(err.message||'バックアップを読み込めませんでした。')}finally{e.target.value=''}};
$('demo').onclick=()=>{selectedId=null;setData({visits:[{id:'demo1',start:'2026-09-20T01:00:00Z',lat:35.6812,lng:139.7671,name:'東京駅（サンプル）',card:false,note:''},{id:'demo2',start:'2026-09-20T03:00:00Z',lat:35.6896,lng:139.7006,name:'新宿（サンプル）',card:false,note:''}],paths:[{start:'2026-09-20T01:00:00Z',points:[[35.6812,139.7671],[35.685,139.735],[35.6896,139.7006]]}]});status('架空のサンプルを表示しています。ご自身の記録ではありません。')};renderSaved();


function showDiagnostic(text){let box=document.getElementById('json-diagnostic');if(!box){box=document.createElement('details');box.id='json-diagnostic';const summary=document.createElement('summary');summary.textContent='ファイル構造の診断（項目名と型のみ）';const info=document.createElement('p');info.className='hint';info.textContent='日時・座標・訪問先などの値は含みません。この欄のテキストをコピーしてチャットに貼ると、対応方法を確認できます。';const area=document.createElement('textarea');area.readOnly=true;area.setAttribute('aria-label','ファイル構造の診断');area.style.cssText='width:100%;height:230px;font-family:monospace;font-size:12px';box.append(summary,info,area);$('status').after(box)}box.hidden=false;box.open=true;box.querySelector('textarea').value=text}
function hideDiagnostic(){const box=document.getElementById('json-diagnostic');if(box)box.hidden=true}
