(function(root){
function coord(v){if(!v)return null;if(typeof v==='string'){const m=v.match(/(?:geo:)?\s*(-?\d+(?:\.\d+)?)\s*°?\s*,\s*(-?\d+(?:\.\d+)?)/);if(m)return valid(+m[1],+m[2]);}if(typeof v==='object'){if(v.latitudeE7!=null)return valid(v.latitudeE7/1e7,v.longitudeE7/1e7);if(v.latLng)return coord(v.latLng);if(v.point)return coord(v.point);return valid(v.latitude??v.lat,v.longitude??v.lng);}return null}
function valid(a,b){return Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a)<=90&&Math.abs(b)<=180?[a,b]:null}
function date(v){if(v==null)return null;const d=new Date(typeof v==='string'&&/^\d+$/.test(v)?Number(v):v);return Number.isFinite(+d)?d.toISOString():null}
function shape(data){const lines=[];function walk(v,path,depth){if(lines.length>=45)return;const type=v===null?'null':Array.isArray(v)?'array':typeof v;lines.push(path+': '+type);if(depth>=4||v===null)return;if(Array.isArray(v)){if(v.length)walk(v[0],path+'[]',depth+1)}else if(typeof v==='object'){for(const k of Object.keys(v).slice(0,16))walk(v[k],path+'.'+k,depth+1)}}walk(data,'root',0);return lines.join('\n')}
function unwrap(data){if(Array.isArray(data))return data;if(!data||typeof data!=='object')return data;const queue=[{v:data,depth:0}];let count=0;while(queue.length&&count++<100){const {v,depth}=queue.shift();if(['semanticSegments','timelineObjects','locations'].some(k=>Array.isArray(v[k])))return v;if(depth<5)for(const [k,val] of Object.entries(v)){if(!val||typeof val!=='object')continue;if(Array.isArray(val)){if(val.some(s=>s&&typeof s==='object'&&('visit' in s||'placeVisit' in s||'timelinePath' in s||'activitySegment' in s)))return val;}else queue.push({v:val,depth:depth+1})}}return data}
function parse(data){data=unwrap(data);if(!data||typeof data!=='object')throw Error('JSONの中にタイムラインの記録が見つかりませんでした。');let visits=[],paths=[],ignored=0;const segments=Array.isArray(data)?data:data.semanticSegments??data.timelineObjects;if(Array.isArray(segments)){for(const s of segments){if(!s||typeof s!=='object'){ignored++;continue}const start=date(s.startTime??s.duration?.startTimestamp??s.placeVisit?.duration?.startTimestamp??s.activitySegment?.duration?.startTimestamp??s.placeVisit?.duration?.startTimestampMs??s.activitySegment?.duration?.startTimestampMs);const end=date(s.endTime??s.placeVisit?.duration?.endTimestamp??s.placeVisit?.duration?.endTimestampMs);const visit=s.visit??s.placeVisit;if(visit){const loc=visit.topCandidate?.placeLocation??visit.topCandidate?.location??visit.location;const c=coord(loc);if(c&&start)visits.push({id:`v${visits.length}`,start,end,lat:c[0],lng:c[1],name:visit.location?.name??visit.topCandidate?.name??'訪問地点',note:'',card:false});else ignored++;}const act=s.activity??s.activitySegment;let pts=s.timelinePath??s.activitySegment?.simplifiedRawPath?.points??s.activitySegment?.waypointPath?.waypoints??[];pts=pts.map(p=>coord(p.point??p)).filter(Boolean);if(!pts.length&&act)pts=[coord(act.start??act.startLocation),coord(act.end??act.endLocation)].filter(Boolean);if(pts.length&&start)paths.push({start,points:pts});}}else if(Array.isArray(data.locations)){let pts=[];for(const p of data.locations){const c=coord(p),start=date(p.timestamp??p.timestampMs);if(c&&start)paths.push({start,points:[c]});else ignored++;}}else throw Error('このJSON形式にはまだ対応していません。semanticSegments、timelineObjects、locationsを含む形式に対応しています。');if(!visits.length&&!paths.length)throw Error('表示できる日時・座標が見つかりませんでした。元のファイルは変更していません。');return{visits,paths,ignored}}
root.TimelineParser={parse,coord,shape};if(typeof module!=='undefined')module.exports=root.TimelineParser;
})(typeof window==='undefined'?globalThis:window);
